services:
  # the webapp
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: my_web_image
    depends_on:
      db:
    # we make sure to start the web service only if the database started healthy
        condition: service_healthy
    networks:
    # connect to the docker network webnet so they can be communication from the DB, apache server and the riverse proxy (traefik)
      - webnet
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: exampledb
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      # use of the docker secret as per the projecr requirement
      - db_user
      - db_password
    volumes:
    # need to mount the html page
      - ./public-html/:/var/www/html/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-router.entrypoints=websecure"
      - "traefik.http.routers.web-router.tls=true"
      - "traefik.http.routers.web-router.rule=Host(`web.local`)"
      - "traefik.http.routers.web-router.service=web-lb"
      - "traefik.http.services.web-lb.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0
    restart: always
    networks:
      - webnet
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: exampledb
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_user
      - db_password
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  traefik:
    image: traefik:v3.0
    command:
      - "--configFile=/traefik/traefik.yml"
    ports:
      - "80:80" # web service
      - "443:443" # https part
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik/traefik.yml
      - ./traefik/dynamic.yml:/traefik/dynamic.yml
    secrets:
      - localhost_crt
      - localhost_key
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
    external: true
volumes:
  db_data:

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
  localhost_crt:
    file: ./secrets/certs/localhost.crt
  localhost_key:
    file: ./secrets/certs/localhost.key
