api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  traefik:
    address: ":8080"

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
log:
  level: DEBUG

accessLog: {}
